name: release

on:
    workflow_dispatch:

jobs:
    build-and-release:
        permissions:
            contents: write

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-24.04, windows-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: "stable"

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"

            - name: Install Wails
              run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

            - name: Build for Linux
              if: runner.os == 'Linux'
              run: |
                  sudo apt update
                  sudo apt install libgtk-3-dev libwebkit2gtk-4.1-dev
                  wails build -tags webkit2_41

            - name: Build for Windows
              if: runner.os == 'Windows'
              run: wails build -nsis

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ runner.os }}-${{ runner.arch }}
                  path: build/bin

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: build/bin/*
                  tag_name: ${{ github.run_id }}
